<?php
declare(strict_types=1);

namespace GibsonOS\Module\Zeus\Enum;

enum QuotaCode: string
{
    case INDEPENDENCE_PERCENT = 'BK621-App-HOME-INDEPENDENCE-PERCENT-FLOW-indep-progress_bar-NOTDISTINGUISH-MASTER_DATA';
    case CO2_WEIGHT = 'BK621-App-HOME-CO2-WEIGHT-FLOW-impact-progress_arc-NOTDISTINGUISH-MASTER_DATA';
    case SAVING_CURRENCY = 'BK621-App-HOME-SAVING-CURRENCY-FLOW-earnings-progress_arc-NOTDISTINGUISH-MASTER_DATA';
    case SOLAR_ENERGY = 'BK621-App-HOME-SOLAR-ENERGY-FLOW-solor-line-NOTDISTINGUISH-MASTER_DATA';
    case LOAD_ENERGY = 'BK621-App-HOME-LOAD-ENERGY-FLOW-consumption-prop_arc-NOTDISTINGUISH-MASTER_DATA';
    case GRID_ENERGY = 'BK621-App-HOME-GRID-ENERGY-FLOW-grid_prop_bar-NOTDISTINGUISH-MASTER_DATA';
    case SOC_ENERGY = 'BK621-App-HOME-SOC-ENERGY-FLOW-battery-prop_bar-NOTDISTINGUISH-MASTER_DATA';
}
